name: CI - Testes Cypress
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  testes:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
 
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
 
      - name: Instalar dependências
        run: npm install
 
      - name: Rodar testes Cypress
        run: npm test
 
      - name: Gerar relatório Allure
        if: always()
        run: npx allure@3.9.0 generate --output allure-report allure-results
 
      - name: Publicar relatório Allure
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report